config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root "homes#top"

  devise_for :admins, controllers: {  
    sessions: "admins/sessions",
    passwords: "admins/passwords"
  }
    namespace :admins do
      resources :users, only: [:index, :edit, :update, :destroy] do
        collection do
          get "destroy_request"
          delete "bulk_deletion"
        end
      end
    end

  devise_for :users,
    controllers: {
      registrations: "users/registrations",
      omniauth_callbacks: "users/omniauth_callbacks",
      passwords: "users/passwords",
      sessions: "users/sessions"
    }
  # ユーザー情報削除申請後のログアウト用
  devise_scope :user do
    get 'users/sign_out', to: 'users/sessions#destroy', as: :sign_out
  end

  resources :users, only: [:show] do
    member do
      get "edit_destroy_request"
      patch "update_destroy_request"
    end
    resources :storages, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  get "/users/:user_id/storages/foods/new", to: "foods#new", as: "new_user_storage_food"
  post "/users/:user_id/storages/foods", to: "foods#create", as: "user_storage_food"
  get "/users/:user_id/storages/foods", to: "foods#index", as: "user_storage_foods"
  get "/users/:user_id/storages/:storage_id/foods/:id/edit", to: "foods#edit", as: "edit_user_storage_food"
  patch "/users/:user_id/storages/:storage_id/foods/:id", to: "foods#update", as: "update_user_storage_food"
  delete "/users/:user_id/storages/:storage_id/foods/:id/", to: "foods#destroy", as: "destroy_user_storage_food"
  get "/users/:user_id/storages/foods/notice", to: "foods#notice", as: "user_storage_foods_notice"

  get "users/:user_id.storages/foods/ajax", to: "foods#ajax", as: "user_storage_foods_ajax"
end

app/models/storage.rb
class Storage < ApplicationRecord
  belongs_to :user
  has_many :foods, dependent: :destroy

  validates :place, presence: true, null: false,
                   length: { maximum: 20 }

  validate :same_user_same_place_cannot_registered

  def same_user_same_place_cannot_registered
    if id.nil?
      if user_id.present? && place.present?
        if Storage.exists?(user_id: user_id, place: place)
          errors.add(:place, "は既に登録済みです。他の場所を登録して下さい")
        end
      end
    end
  end
  
end

app/controllers/storages_controller.rb
class StoragesController < ApplicationController
  include AjaxHelper
  before_action :admin_not_viewable
  before_action :authenticate_user! 
  before_action :set_user
  before_action :set_storage, only: [:edit, :update, :destroy]

  def index
    @storages = Storage.where(user_id: current_user.id).page(params[:page]).per(5)
  end

  def new
    @storage = Storage.new
  end

  def create
    @storage = Storage.new(storage_params)
    respond_to do |format|
      if @storage.save
        format.html
        format.js { render ajax_redirect_to(user_storages_url), 
                    flash[:notice] = "#{@storage.place}を登録しました。" }
      else
        format.html { render :new }
        format.js { render "messages/storage_errors" }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @storage.update(storage_params)
        format.html
        format.js { render ajax_redirect_to(user_storages_url), 
                    flash[:notice] = "保管場所情報を更新しました。" }
      else
        format.html { render :edit }
        format.js { render "messages/storage_errors" }
      end
    end
  end

  def destroy
    @storage.destroy
    flash[:success] = "#{@storage.place}の情報を削除しました。"
    redirect_to user_storages_url
  end

  private
    def storage_params
      params.require(:storage).permit(:place, :user_id)
    end

end

app/helpers/storages_helper.rb
module StoragesHelper
end

app/views/storages/_edit.html.slim
- provide(:button_text, "更新する") 

.modal-dialog.modal-lg
  .modal-content.modal--color
    .modal-body
      button.float-end.btn-close[data-bs-dismiss="modal"]
      br
      h1 保管場所編集

      .js-message-errors

      = form_with model: @storage, url: user_storage_path(@user) do |f|
        = render "users/shared/error_messages", resource: @storage
        = render "form", f: f

app/views/storages/_form.html.slim
  = f.label :place, class: "label--fontstyle"
  = f.text_field :place, autofocus: true, required: true, class: "form-control"

  = f.hidden_field :user_id, value: current_user.id

  .btn__storages--center
    = f.submit yield(:button_text), class: "btn main__btn"

app/views/storages/_new.html.slim
- provide(:button_text, "登録する")

.modal-dialog.modal-lg
  .modal-content.modal--color
    .modal-body
      button.float-end.btn-close[data-bs-dismiss="modal"]
      br
      h1 保管場所登録

      .js-message-errors

      = form_with model: @storage, url: user_storages_path(@user)do |f|
        = render "users/shared/error_messages", resource: @storage
        = render "form", f: f

app/views/storages/edit.js.erb
$("#storage-edit").html("<%= escape_javascript(render 'storages/edit') %>");
$("#storage-edit").modal("show");

app/views/storages/index.html.slim
- provide(:title, "All storage")

h1 保管場所一覧
.row
  .col-md-8.offset-md-2
    / = paginate(@storages)
    .btn__storages--center
      = link_to "保管場所を追加する", new_user_storage_path(@user), remote: true, class: "btn main__btn"
      = link_to "食品一覧へ", user_storage_foods_path(@user), class: "btn main__btn"
    
    - if @storages.present?
      table.table.text--center.table__font-color
        tr
          th.noborder = Storage.human_attribute_name :place
          th.noborder
          
        - @storages.each do |storage|
          tr
            td = storage.place
            td
              = link_to "編集", edit_user_storage_path(@user, storage), remote: true, class: "btn btn--edit btn--margin"
              = link_to "削除", user_storage_path(@user, storage), method: :delete,
                data: { confirm: "削除してよろしいですか？" },
                class: "btn btn--destroy btn--margin"
      = paginate(@storages)
    
    - else
      .text--center
        br
        p 保管場所が登録されていません。

app/views/storages/new.js.erb
$("#storage-new").html("<%= escape_javascript(render 'storages/new') %>");
$("#storage-new").modal("show");