config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root "homes#top"

  devise_for :admins, controllers: {  
    sessions: "admins/sessions",
    passwords: "admins/passwords"
  }
    namespace :admins do
      resources :users, only: [:index, :edit, :update, :destroy] do
        collection do
          get "destroy_request"
          delete "bulk_deletion"
        end
      end
    end

  devise_for :users,
    controllers: {
      registrations: "users/registrations",
      omniauth_callbacks: "users/omniauth_callbacks",
      passwords: "users/passwords",
      sessions: "users/sessions"
    }
  # ユーザー情報削除申請後のログアウト用
  devise_scope :user do
    get 'users/sign_out', to: 'users/sessions#destroy', as: :sign_out
  end

  resources :users, only: [:show] do
    member do
      get "edit_destroy_request"
      patch "update_destroy_request"
    end
    resources :storages, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  get "/users/:user_id/storages/foods/new", to: "foods#new", as: "new_user_storage_food"
  post "/users/:user_id/storages/foods", to: "foods#create", as: "user_storage_food"
  get "/users/:user_id/storages/foods", to: "foods#index", as: "user_storage_foods"
  get "/users/:user_id/storages/:storage_id/foods/:id/edit", to: "foods#edit", as: "edit_user_storage_food"
  patch "/users/:user_id/storages/:storage_id/foods/:id", to: "foods#update", as: "update_user_storage_food"
  delete "/users/:user_id/storages/:storage_id/foods/:id/", to: "foods#destroy", as: "destroy_user_storage_food"
  get "/users/:user_id/storages/foods/notice", to: "foods#notice", as: "user_storage_foods_notice"

  get "users/:user_id.storages/foods/ajax", to: "foods#ajax", as: "user_storage_foods_ajax"
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :storage
  has_one :user, through: :storage, source: :user

  validates :fname, presence: true, null: false,
                    length: { maximum: 40 }
  validates :quantity, presence: true
  validates :quantity, numericality: { greater_than_or_equal_to: 1, less_than: 30 },
                       allow_blank: true, on: :create
  validates :quantity, numericality: { greater_than_or_equal_to: 0, less_than: 30 },
                       allow_blank: true, on: :update # 更新時は0も可
  validates :purchase, presence: true, null: false
  validate :purchasedate_earlier_than_not_today_possible,
           :expirationdate_before_inputdate_is_not_possible
          #  :noticedate_before_inputdate_is_not_possible,
          #  :noticedate_after_expirationdate_is_not_possible,
          #  :no_expirationdate_cannot_enter_noticedate
           
  # 入力日より先の購入日は入力不可
  def purchasedate_earlier_than_not_today_possible
    if purchase.present? && purchase > Date.today
      errors.add(:purchase, "に本日より先の日付は入力できません") 
    end
  end

  # 入力日以前の使い切り期限は入力不可
  def expirationdate_before_inputdate_is_not_possible
    if expiration.present? && expiration <= Date.today
      errors.add(:expiration, "に本日または本日以前の日付は入力できません")
    end
  end

  # # 入力日以前のお知らせ日は入力不可
  # def noticedate_before_inputdate_is_not_possible
  #   if notice.present? && notice <= Date.today
  #     errors.add(:notice, "に本日以前の日付は入力できません")
  #   end
  # end
  # # 使い切り期限より先のお知らせ日は入力不可
  # def noticedate_after_expirationdate_is_not_possible
  #   if notice.present? && notice > expiration
  #     errors.add(:notice, "に使い切り期限より先の日付は入力できません")
  #   end
  # end

  # # 使い切り期限が存在しない時、お知らせ日は入力不可
  # def no_expirationdate_cannot_enter_noticedate
  #   if notice.present? && expiration.nil?
  #     errors.add(:notice, "は入力できません。使い切り期限を指定してください")
  #   end
  # end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  include AjaxHelper
  before_action :admin_not_viewable
  before_action :authenticate_user! 
  before_action :set_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_storage, only: [:edit, :update, :destroy]
  before_action :set_storages, only: [:new, :create, :edit, :update]
  before_action :set_food, only: [:edit, :update, :destroy]
  before_action :set_notices, only: [:index, :notice]

  def index
    @foods = current_user.foods.all
    @storages = current_user.storages.all
  end

  def ajax
    if params[:search].present?
      @foods = Food.where(storage_id: params[:search])
      @storage = Storage.find(params[:search])
    else
      @foods = current_user.foods.all
      @storages = current_user.storages.all
    end
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    respond_to do |format|
      if @food.save
        format.html
        format.js { render ajax_redirect_to(user_storage_foods_url), 
                    flash[:notice] = "#{@food.fname}の情報を登録しました。" }
      else
        format.html { render :new }
        format.js { render "messages/food_errors" }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @food.update(food_params)
        if @food.quantity == 0
          @food.destroy # この時点で数量0の場合は削除処理を行う
          format.html
          format.js { render ajax_redirect_to(user_storage_foods_url), 
                      flash[:notice] = "#{@food.fname}を使い切りました。" }
        else
          format.html
          format.js { render ajax_redirect_to(user_storage_foods_url), 
                      flash[:notice] = "#{@food.fname}の情報を更新しました。" }
        end
      else
        format.html { render :edit }
        format.js { render "messages/food_errors" }
      end
    end
  end

  def notice
  end

  def destroy
    @food.destroy
    flash[:notice] = "#{@food.fname}の情報を削除しました。"
    redirect_to user_storage_foods_url(current_user)
  end

  private
    def food_params
      params.require(:food).permit(:fname, :quantity, :purchase, :expiration, :notice, :storage_id)
    end

    def set_food
      @food = Food.find(params[:id])
    end

    def set_storages
      @storages = Storage.where(user_id: current_user.id)
    end

    def set_notices
      @notices = current_user.foods.where(expiration: Date.current.next_day).or(current_user.foods.where(expiration: Date.current.since(2.days)))
    end
end

app/helpers/foods_helper.rb
module FoodsHelper
  # 保管場所表示
  def where_storage(storage_id)
    storage = Storage.find(storage_id)
    storage.place
  end

end

app/views/foods/_edit.html.slim
- provide(:button_text, "更新する") 

.modal-dialog.modal-lg
  .modal-content.modal--color
    .modal-body
      button.float-end.btn-close[data-bs-dismiss="modal"]
      br
      h1 食品編集

      .js-message-errors

      = form_with model: @food, url: update_user_storage_food_path(@storage.user_id, @storage.id, @food) do |f|
        = render "users/shared/error_messages", resource: @food
        = render "form", f: f

app/views/foods/_foods.html.slim
- if foods.blank?
  br
  p この保管場所に登録されている食品はありません。
- else
  / = paginate(@foods, remote: true)
  table.table.text--center.table__font-color
    tr
      th.noborder = Food.human_attribute_name :fname
      th.noborder = Food.human_attribute_name :quantity
      th.noborder = Food.human_attribute_name :purchase
      th.noborder = Food.human_attribute_name :expiration
      th.noborder = Storage.human_attribute_name :place
      th.noborder

      - foods.each do |food|
        tr class="#{(food.expiration.present? && Date.current > food.expiration ? " foods__fontcolor-red" : "")}"
          td = food.fname
          td = food.quantity
          td = l(food.purchase, formats: :long) if food.purchase.present?
          td = l(food.expiration, formats: :long) if food.expiration.present?
          td = where_storage(food.storage_id)
          td
            = link_to "編集", edit_user_storage_food_path(current_user.id, food.storage_id, food), remote: true, class: "btn btn--edit btn--margin"
            = link_to "削除", destroy_user_storage_food_path(current_user.id, food.storage_id, food), method: :delete,
              data: { confirm: "削除してよろしいですか？" },
              class: "btn btn--destroy btn--margin"

app/views/foods/_form.html.slim
  = f.label :fname, class: "label--fontstyle"
  = f.text_field :fname, autofocus: true, class: "form-control", required: true

  = f.label :quantity, class: "label--fontstyle"
  = f.number_field :quantity, class: "form-control", required: true

  = f.label :purchase, class: "label--fontstyle"
  = f.date_field :purchase, value: Date.current, class: "form-control", required: true

  = f.label :expiration, class: "label--fontstyle"
  = f.date_field :expiration, class: "form-control"

  = f.label :storage_id, class: "label--fontstyle"
  = f.collection_select :storage_id, @storages, :id, :place, { include_blank: true }, { class: "form-control", required: true }

  .btn__storages--center
    = f.submit yield(:button_text), class: "btn main__btn"

app/views/foods/_new.html.slim
- provide(:button_text, "登録する")

.modal-dialog.modal-lg
  .modal-content.modal--color
    .modal-body
      button.float-end.btn-close[data-bs-dismiss="modal"]
      br
      h1 食品登録

      .js-message-errors

      = form_with model: @food, url: user_storage_food_path(@user) do |f|
        = render "users/shared/error_messages", resource: @food
        = render "form", f: f

app/views/foods/_notice.html.slim
.modal-dialog.modal-lg
  .modal-content.modal--color
    .modal-body
      button.float-end.btn-close[data-bs-dismiss="modal"]
      br
      h1 使い切り期限のお知らせ
      br
        table.table.text--center
            tr
              th.border--color = Food.human_attribute_name :fname
              th.border--color = Food.human_attribute_name :quantity
              th.border--color = Food.human_attribute_name :purchase
              th.border--color = Food.human_attribute_name :expiration
              th.border--color = Storage.human_attribute_name :place
              th.border--color
            
            - @notices.each do |notice|
              tr
                td.noborder = notice.fname
                td.noborder = notice.quantity
                td.noborder = l(notice.purchase, formats: :long) if notice.purchase.present?
                td.noborder = l(notice.expiration, formats: :long) if notice.expiration.present?
                td.noborder = where_storage(notice.storage_id)
                td.noborder
                  = link_to "削除", destroy_user_storage_food_path(current_user.id, notice.storage_id, notice), method: :delete,
                    data: { confirm: "削除してよろしいですか？" },
                    class: "btn btn--destroy btn--margin"

app/views/foods/ajax.js.erb
$(".foods__index--search").html("<%= escape_javascript(render 'foods/foods', { foods: @foods } ) %>");

app/views/foods/edit.js.erb
$("#food-edit").html("<%= escape_javascript(render 'foods/edit') %>");
$("#food-edit").modal("show");

app/views/foods/index.html.slim
- provide(:title, "All foods")

h1 食品一覧
.row
  .col-md-10.offset-md-1
    .btn__storages--center
      = link_to "食品を追加する", new_user_storage_food_path(current_user), remote: true, class: "btn main__btn #{ ' disabled' unless @storages.present? }"
      = link_to "保管場所一覧へ", user_storages_path(current_user), class: "btn main__btn"

      - if @storages.blank?
        br
        p 保管場所を登録してください。
        p 保管場所登録後、食品登録ができるようになります。

      - elsif @foods.present?
        ul
          li.index__option--inline
            = link_to_if @notices.present?, "【使い切り期限のお知らせ】", user_storage_foods_notice_path, remote: true, class: "main__link"
            - if @notices.present?
              span style="color:#b94047;" class="notices" まもなく使い切り予定の食品が#{@notices.count}点あります。
          li.index__option--inline
            = form_with url: user_storage_foods_ajax_path(current_user), method: :get, remote: true do |f|
              = f.submit "絞り込み", id: "search--place"
              = f.collection_select :search, @storages, :id, :place, { include_blank: "全ての保管場所" }, { class: "form-control", id: "select--place" }
  
        .foods__index--search
          = render "foods/foods", foods: @foods

      - else
          br
          br
          p 食品が登録されていません。

app/views/foods/new.js.erb
$("#food-new").html("<%= escape_javascript(render 'foods/new') %>");
$("#food-new").modal("show");

app/views/foods/notice.js.erb
$("#food-notice").html("<%= escape_javascript(render 'foods/notice') %>");
$("#food-notice").modal("show");