config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root "homes#top"

  devise_for :admins, controllers: {  
    sessions: "admins/sessions",
    passwords: "admins/passwords"
  }
    namespace :admins do
      resources :users, only: [:index, :edit, :update, :destroy] do
        collection do
          get "destroy_request"
          delete "bulk_deletion"
        end
      end
    end

  devise_for :users,
    controllers: {
      registrations: "users/registrations",
      omniauth_callbacks: "users/omniauth_callbacks",
      passwords: "users/passwords",
      sessions: "users/sessions"
    }
  # ユーザー情報削除申請後のログアウト用
  devise_scope :user do
    get 'users/sign_out', to: 'users/sessions#destroy', as: :sign_out
  end

  resources :users, only: [:show] do
    member do
      get "edit_destroy_request"
      patch "update_destroy_request"
    end
    resources :storages, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  get "/users/:user_id/storages/foods/new", to: "foods#new", as: "new_user_storage_food"
  post "/users/:user_id/storages/foods", to: "foods#create", as: "user_storage_food"
  get "/users/:user_id/storages/foods", to: "foods#index", as: "user_storage_foods"
  get "/users/:user_id/storages/:storage_id/foods/:id/edit", to: "foods#edit", as: "edit_user_storage_food"
  patch "/users/:user_id/storages/:storage_id/foods/:id", to: "foods#update", as: "update_user_storage_food"
  delete "/users/:user_id/storages/:storage_id/foods/:id/", to: "foods#destroy", as: "destroy_user_storage_food"
  get "/users/:user_id/storages/foods/notice", to: "foods#notice", as: "user_storage_foods_notice"

  get "users/:user_id.storages/foods/ajax", to: "foods#ajax", as: "user_storage_foods_ajax"
end

app/views/admins/shared/_error_messages.html.slim
- if resource.errors.any?
  #error_explanation
    h2
      = I18n.t("errors.messages.not_saved",
      -                  count: resource.errors.count,
      -                  resource: resource.class.model_name.human.downcase)
    ul
      - resource.errors.full_messages.each do |message|
        li
          = message

app/views/admins/shared/_links.html.slim
/ Admin
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  br
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  br
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  p#link__password-forget
    |  パスワードをお忘れの方は
    = link_to "こちら", new_password_path(resource_name)
  / br
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  br
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
.link__admin-signin  
  | 一般ユーザーログインは
  = link_to "こちら", new_user_session_path