config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root "homes#top"

  devise_for :admins, controllers: {  
    sessions: "admins/sessions",
    passwords: "admins/passwords"
  }
    namespace :admins do
      resources :users, only: [:index, :edit, :update, :destroy] do
        collection do
          get "destroy_request"
          delete "bulk_deletion"
        end
      end
    end

  devise_for :users,
    controllers: {
      registrations: "users/registrations",
      omniauth_callbacks: "users/omniauth_callbacks",
      passwords: "users/passwords",
      sessions: "users/sessions"
    }
  # ユーザー情報削除申請後のログアウト用
  devise_scope :user do
    get 'users/sign_out', to: 'users/sessions#destroy', as: :sign_out
  end

  resources :users, only: [:show] do
    member do
      get "edit_destroy_request"
      patch "update_destroy_request"
    end
    resources :storages, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  get "/users/:user_id/storages/foods/new", to: "foods#new", as: "new_user_storage_food"
  post "/users/:user_id/storages/foods", to: "foods#create", as: "user_storage_food"
  get "/users/:user_id/storages/foods", to: "foods#index", as: "user_storage_foods"
  get "/users/:user_id/storages/:storage_id/foods/:id/edit", to: "foods#edit", as: "edit_user_storage_food"
  patch "/users/:user_id/storages/:storage_id/foods/:id", to: "foods#update", as: "update_user_storage_food"
  delete "/users/:user_id/storages/:storage_id/foods/:id/", to: "foods#destroy", as: "destroy_user_storage_food"
  get "/users/:user_id/storages/foods/notice", to: "foods#notice", as: "user_storage_foods_notice"

  get "users/:user_id.storages/foods/ajax", to: "foods#ajax", as: "user_storage_foods_ajax"
end

app/views/layouts/_header.html.slim
nav.navbar.navbar-expand-lg.fixed-top style="background-color: #856859"
  .container-fluid
    = link_to "Pantry", root_path, id: "logo" 
    ul.navbar-nav
      - if admin_signed_in?
        li = link_to "ユーザー一覧", admins_users_path, class: "nav__btn"
        li.nav-item.dropdown
          a.nav-link.link--hover.dropdown-toggle href="#" id="navbar__dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"
            = "管理者"
          ul.dropdown-menu.dropdown-menu-end#menu--color aria-labelledby="navbarDropdown"
            li = link_to  "ログアウト", destroy_admin_session_path, method: :delete, class: "dropdown-item" 

      - elsif user_signed_in?
        li = link_to "食品一覧", user_storage_foods_path(current_user), class: "nav__btn"
        li = link_to "保管場所一覧", user_storages_path(current_user), class: "nav__btn"
        li.nav-item.dropdown
          a.nav-link.link__hover.dropdown-toggle href="#" id="navbar__dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"
            = current_user.uname
          ul.dropdown-menu.dropdown-menu-end#menu--color aria-labelledby="navbarDropdown"
            li = link_to  "ユーザー情報", user_path(current_user), class: "dropdown-item"
            li = link_to  "ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item"

      - else
        li = link_to "ログイン", new_user_session_path, class: "nav__btn"
        li = link_to "新規登録", new_user_registration_path, class: "nav__btn"

app/views/layouts/_shim.html.slim
/ [if lt IE 9]
script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js" 
/ [endif]

app/views/layouts/_validation_errors.html.slim
- if instance.errors.full_messages.present? 
  .error_explanation.js-message-errors
    .alert.alert-danger role="alert"
      = I18n.t("errors.messages.not_saved",
          count: instance.errors.count,
          resource: instance.class.model_name.human.downcase)
    ul
      - instance.errors.full_messages.each do |msg|
        li = "#{msg}。"

app/views/layouts/application.html.slim
/ slimとは
/ Ruby製のテンプレートエンジン、高速・軽量
/ htmlの閉じタグ不要、条件分岐などのend不要、インデントによって階層構造を表現するためずれるとエラーになる
doctype html
html
  head
    title
      = full_title(yield(:title))
       | Pantry
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    / jQuery読み込み。bootstrapより先でないといけない
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = render "layouts/shim"
  body
    = render "layouts/header"
    .container
      - flash.each do |message_type, msg|
        = content_tag(:div, msg.html_safe , class: "alert alert-#{bootstrap_alert(message_type)} alert--position")
      = yield
      = debug(params) if Rails.env.development?

  / モーダルウィンドウ表示
  div class="modal fade" id="destroy-request" tabindex="-1" role="dialog" aria-hidden="true"
  div class="modal fade" id="food-new" tabindex="-1" role="dialog" aria-hidden="true"
  div class="modal fade" id="food-edit" tabindex="-1" role="dialog" aria-hidden="true"
  div class="modal fade" id="food-notice" tabindex="-1" role="dialog" aria-hidden="true"
  div class="modal fade" id="storage-new" tabindex="-1" role="dialog" aria-hidden="true"
  div class="modal fade" id="storage-edit" tabindex="-1" role="dialog" aria-hidden="true"